modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/${repoUser}/${repoName}/issues"
license = "LGPL-3.0"

[[mods]] #mandatory
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
updateJSONURL = "https://raw.githubusercontent.com/${repoUser}/${repoName}/${minecraft_version}/update.json"
description = '''Change the way you cut trees.'''
displayURL = "https://www.curseforge.com/minecraft/mc-mods/falling-tree"
logoFile = "logo.png"
authors = "RakSrinaNa"

[[dependencies.fallingtree]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.fallingtree]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.fallingtree]]
modId = "cloth-config"
mandatory = false
versionRange = "[6.0.0,)"
ordering = "NONE"
side = "CLIENT"
