modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/${repoUser}/${repoName}/issues"
license = "LGPL-3.0"

[[mods]] #mandatory
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
description = '''Change the way you cut trees.'''
displayURL = "https://www.curseforge.com/minecraft/mc-mods/falling-tree"
logoFile = "logo.png"
authors = "Rakambda"

[[dependencies.fallingtree]]
modId = "forge"
mandatory = true
versionRange = "[46.0.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.fallingtree]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.fallingtree]]
modId = "cloth-config"
mandatory = false
versionRange = "[11.0.99,)"
ordering = "NONE"
side = "CLIENT"
