daysUntilStale: 14
daysUntilClose: 7
exemptLabels:
  - 🙏keep open
staleLabel: "status: ⌛ stale"
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.
closeComment: false
