modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/RakSrinaNa/FallingTree/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/falling-tree"
logoFile="logo.png"
# credits=""
authors = "RakSrinaNa"
license = "GPL-3.0"

[[mods]] #mandatory
	modId="falling_tree"
	version="${file.jarVersion}"
	displayName="Falling Tree"
	updateJSONURL="https://raw.githubusercontent.com/RakSrinaNa/FallingTree/1.15.2/update.json"
	description='''Cut trees in one cut'''

[[dependencies.falling_tree]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.0,)"
    ordering="NONE"
	side="BOTH"
[[dependencies.falling_tree]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
