modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/${project.repoUser}/${project.repoName}/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/falling-tree"
logoFile="logo.png"
# credits=""
authors = "RakSrinaNa"
license = "GPL-3.0"

[[mods]] #mandatory
    modId="${project.mod_id}"
    version="${project.version}"
    displayName = "${project.modName}"
updateJSONURL = "https://raw.githubusercontent.com/${project.repoUser}/${project.repoName}/${project.minecraft_version}-forge/update.json"
description = '''Change the way you cut trees.'''

[[dependencies.falling_tree]]
modId = "forge"
mandatory = true
versionRange = "[35.0.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.falling_tree]]
modId = "minecraft"
mandatory = true
versionRange = "[${project.minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.falling_tree]]
modId = "cloth-config"
mandatory = false
ordering = "NONE"
side = "CLIENT"
