# Fabric https://modmuss50.me/fabric.html

[versions]
modmenu-version = "2.0.10"
cloth-config-fabric-version = "5.0.38"
cloth-config-forge-version = "5.0.38"
lombok-version = "1.18.20"
minecraft-version = "21w39a"
fabric-loader-version = "0.11.7"
fabric-api-version = "0.40.5+1.18"
forge-version = "1.17.1-37.0.59"

curse-version = "1.4.0"
modrinth-version = "1.2.1"
names-version = "0.39.0"
fabric-loom-version = "0.10-SNAPSHOT"

[libraries]
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu-version" }
clothConfigFabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "cloth-config-fabric-version" }
clothConfigForge = { group = "me.shedaniel.cloth", name = "cloth-config-forge", version.ref = "cloth-config-forge-version" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok-version" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft-version" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader-version" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api-version" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge-version" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]

[plugins]
curse = { id = "com.matthewprenger.cursegradle", version.ref = "curse-version"}
modrinth = { id = "com.modrinth.minotaur", version.ref = "modrinth-version"}
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
loom = { id = "fabric-loom", version.ref = "fabric-loom-version" }
