[versions]
junit-version = "5.7.2"
log4j-version = "2.14.1"
glfw-version = "3.2.2"
guava-version = "21.0"
commons-lang3-version = "3.12.0"
gson-version = "2.8.6"
brigadier-version = "1.0.17"
modmenu-version = "2.0.0-beta.4"
cloth-config-fabric-version = "5.0.23"

[libraries]
junit_jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-version" }
log4jApi = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j-version" }
lwjglGlfw = { group = "org.lwjgl", name = "lwjgl-glfw", version.ref = "glfw-version" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava-version" }
commonsLang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3-version" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson-version" }
brigadier = { group = "com.mojang", name = "brigadier", version.ref = "brigadier-version" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu-version" }
clothConfigFabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "cloth-config-fabric-version" }

[bundles]
junit = ["junit_jupiter"]
