name: Release

on:
  release:
    types: [created]

env:
  APP_JAVA_VERSION: 16

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.5

      - name: Restore keystore
        run: |
          echo "${{ secrets.KEYSTORE_FORGE_MODS }}" > keystoreForgeMods.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_FORGE_MODS_PASSPHRASE }}" --batch keystoreForgeMods.jks.asc > keystoreForgeMods.jks

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set gradle permissions
        run: chmod +x gradlew

      - name: Push on stores
        uses: gradle/gradle-build-action@v2.0-beta.4
        with:
          arguments: |
            build
            curseforge
            publishModrinth
            -Pchangelog="[Changelog](${{ steps.get_release.outputs.html_url }})"
            -PcurseforgeApiKey="${{ secrets.CURSEFORGE_API_KEY }}"
            -PmodrinthToken="${{ secrets.MODRINTH_TOKEN }}"
            -PforgeKeyStore=keystoreForgeMods.jks
            -PforgeKeyStoreAlias=${{ secrets.KEYSTORE_FORGE_MODS_ALIAS }}
            -PforgeKeyStorePass=${{ secrets.KEYSTORE_FORGE_MODS_STORE_PASS }}
            -PforgeKeyStoreKeyPass=${{ secrets.KEYSTORE_FORGE_MODS_KEY_PASS }}
            -PforgeSignSHA1=f927f4701bf4c0620c7bd0a501ce278f5e5ecc62
